service: vision

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::383624281795:role/ServerlessFrameworkRole
  stackTags:
    slsApp: vision

plugins:
  - serverless-webpack
  - serverless-prune-plugin

functions:
  create: ${file(src/functions/create/function.yml):create}
  delete: ${file(src/functions/delete/function.yml):delete}
  get: ${file(src/functions/get/function.yml):get}
  update: ${file(src/functions/update/function.yml):update}

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  prune:
    automatic: true
    number: 2

package:
  individually: true

resources:
  - ${file(src/resources/dynamodb.yml)}
