service: vision

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role: ${env:IAM_ROLE}
  stackTags:
    slsApp: vision
  httpApi:
    authorizers:
      visionApiAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
            - ''
            - - 'https://cognito-idp.'
              - 'us-east-1'
              - '.amazonaws.com/'
              - Ref: CognitoUserPoolVisionUserPool
        audience: !Ref CognitoUserPoolClient
  environment:
    DOMAIN_SUFFIX: djklagqewryuias14sd678

plugins:
  - serverless-webpack
  - serverless-prune-plugin

functions:
  create: ${file(src/functions/create/function.yml):create}
  delete: ${file(src/functions/delete/function.yml):delete}
  get: ${file(src/functions/get/function.yml):get}
  update: ${file(src/functions/update/function.yml):update}
  autoConfirm: ${file(src/functions/autoConfirm/function.yml):autoConfirm}
  postConfirm: ${file(src/functions/postConfirm/function.yml):postConfirm}

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  prune:
    automatic: true
    number: 2

package:
  individually: true

resources:
  - ${file(src/resources/resources.yml)}
